### ISSUE TITLE
Font van huisstijl

### ISSUE THREAD

**Issue by Anna-Kyra** [lemuelmgsn/the-startup-responsive-interactieve-website#6]
```CSS
/* cyrillic-ext */
@font-face {
    font-family: 'Open Sans';
    font-style: italic;
    font-weight: 300;
    font-stretch: 100%;
    font-display: swap;
    src: url(https://fonts.gstatic.com/s/opensans/v40/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWtE6FxZCJgvAQ.woff2) format('woff2');
    unicode-range: U + 0460-052F, U + 1C80-1C88, U + 20B4, U + 2DE0-2DFF, U + A640-A69F, U + FE2E-FE2F;
}
```
> Van het CSS2 bestand ^^

-	Je kan met inspecteren de fonts van de grrr.tech huisstijl downloaden i.p.v Open Sans te gebruiken
